federation_version: =2.7.0
subgraphs:
  books:
    routing_url: http://localhost:3000/graphql
    schema:
      file: ./books/schema.graphql
  reviews:
    routing_url: http://localhost:3500/graphql
    schema:
      file: ./reviews/schema.graphql